name: Build and test container
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build_and_test:
    name: Build and test container 
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          echo "Remove old crap"
          sudo apt-get -y remove docker docker-engine docker.io containerd runc
          sudo apt-get -y install ca-certificates curl gnupg lsb-release
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get -y update
          sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin
      - name: Get repository
        uses: actions/checkout@v2
      - name: Build Docker container
        run: docker build --label "org.opencontainers.image.source=https://github.com/speedy-beaver/calibre-downloader" -t calibre-downloader .
      - name: Test a download
        run: |
          mkdir testdownload
          docker run -e RECIPE="The Verge" -v $(pwd)/testdownload:/tmp/calibre --rm calibre-downloader
      - name: Show the downloads
        run: if [ -f "testdownload/The Verge.epub" ] ; then echo "Success" ; else false ; fi
      - name: Check where is the recipe
        run: docker run -v $(pwd)/testdownload:/tmp/calibre --rm calibre-downloader find / -name "*economist.recipe" 
      - name: Check where is find
        run: docker run -v $(pwd)/testdownload:/tmp/calibre --rm calibre-downloader which find
      - name: Check the environment
        run: docker run -v $(pwd)/testdownload:/tmp/calibre --rm calibre-downloader env        
