name: Build and test container
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build_and_test:
    name: Build and test container 
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          echo "Remove old crap"
          sudo apt-get -y remove docker docker-engine docker.io containerd runc
          sudo apt-get -y install ca-certificates curl gnupg lsb-release
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get -y update
          sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      - name: Get repository
        uses: actions/checkout@v2
      - name: Build Docker container
        run: docker build --label "org.opencontainers.image.source=https://github.com/speedy-beaver/calibre-downloader" -t calibre-downloader .
      - name: Test a download
        run: |
          mkdir testdownload
          docker run -e RECIPE="The Verge" -v $(pwd)/testdownload:/tmp/calibre --rm calibre-downloader
      - name: Show the downloads
        run: ls testdownload
      - name: Test the downloads
        run: if [ -f "testdownload/The Verge.epub" ] ; then echo "Success" ; else false ; fi   
